api_gateway:
  rest_api_id: abcdefg123
aws:
  account_id: '137568342316'
  role_arn: arn:aws:iam::137568342316:role/SageMakerExecutionRole
deployment_status:
  api_gateway: 'Failed (AWS Error: AccessDeniedException)'
  api_url: https://xyz123.execute-api.us-east-1.amazonaws.com/prod/predict
  frontend: Pending
  lambda_function: 'Failed (AWS Error: AccessDeniedException)'
  last_run: '2025-12-04 13:36:20'
  model_endpoint: 'Failed (AWS Error: ValidationException)'
  s3_bucket: Success
frontend:
  port: 8501
  theme: light
lambda:
  function_name: your-sleep-predictor-lambda-name
project:
  region: us-east-1
s3:
  bucket_name: sleep-disorder-mlops-bucket
  model_s3_key: sagemaker-tuning-output/svm-tuning-251203-2103-002-c8ccdacc/output/model.tar.gz
sagemaker:
  endpoint_name: sleep-disorder-svm-prod-v1
  instance_count: 1
  instance_type: ml.t2.medium
