aws:
  account_id: '137568342316'
  role_arn: arn:aws:iam::137568342316:role/SageMakerExecutionRole
deployment_status:
  api_gateway: Success
  api_url: https://xyz123.execute-api.us-east-1.amazonaws.com/prod/predict
  frontend: Pending
  last_run: '2025-12-04 12:38:46'
  model_endpoint: Success
  s3_bucket: Success
frontend:
  port: 8501
  theme: light
project:
  name: sleep-disorder-mlops
  region: us-east-1
  version: 1.0.0
s3:
  bucket_name: sleep-disorder-mlops-bucket
  model_s3_key: sagemaker-tuning-output/svm-tuning-251203-2103-002-c8ccdacc/output/model.tar.gz
sagemaker:
  endpoint_name: sleep-disorder-svm-prod-v1
  instance_count: 1
  instance_type: ml.t2.medium
